### ISSUE TITLE
Detailed Menu Item View

### ISSUE THREAD

**Issue by NicolasBuscarini** [Org-FoodService/DotNetMVCFoodService#8]
**Story:**

**As** a user of FoodService, **I want** to be able to click on a menu item to view a detailed description of the dish, including ingredients, an image, and an elaborate description, **so that I can make informed decisions about what to order.**

**Acceptance Criteria:**

1. **Menu Display:**
   - Upon accessing the menu in the user interface, items should be presented clearly and organized.

2. **Click on Item:**
   - When a user clicks on a specific menu item, a dedicated window or page should open to display the details of that item.

3. **Detailed Description:**
   - The item's detail page should include a comprehensive description of the dish, highlighting its main ingredients, preparation methods, and special characteristics.
  
4. **Dish Image:**
   - A high-quality image of the dish should be displayed along with the detailed description to provide a visual representation of the item.

5. **Ingredient List:**
   - A complete list of ingredients used in preparing the dish should be presented to inform customers about the components of the item.

6. **Back Button:**
   - There should be a clearly visible button or link to return to the main menu after viewing the item details.

7. **Responsiveness:**
   - The item detail page should be responsive and adapt properly to different screen sizes to ensure a consistent experience on mobile devices and desktops.

**Comment by Rafael-Oliveira-Gomes** [comment]
error when runninh the project
